services:
  cats:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./v_cats:/v_cats
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
