# Generated by Django 4.2.7 on 2023-11-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=30)),
                ('hairiness', models.CharField(choices=[('s', 'маленькая'), ('m', 'средняя'), ('l', 'высокая')], max_length=30)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
